--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/OiranCage/ItemUtils
build-by-default: true
branches:
- main
projects:
  ItemUtils:
    path: ""
    libs:
      - src: CortexPE\Commando\Commando
        version: ^3.0
        branch: PM4
...
