name: ItemUtils
main: oirancage\itemutils\Main
version: 1.0.0
api: 4.0.0
author: OiranCage
authors:
  - famima65536
description: Rich item utils
src-namespace-prefix: oirancage\itemutils
permissions:
  itemutils.command.duplicate:
    default: op
    description: allow to duplicate item.
  itemutils.command.export:
    default: op
    description: allow to export item information in serialized json format.
  itemutils.command.import:
    default: op
    description: allow to import item information from serialized json format.